---

- 
  name: play 1  
  hosts: localhost
  become: true
  tasks:
    - name: ejecutar un comando
      command: ip a

    - name: ejecutar un script
      script: prueba.sh
    
    - name: Instalar Git
      apt: name=git state=latest update_cache=yes

    - name: Instalar las herramientas de la aplicacion web
      apt: name={{ item }} state=latest
      with_items:
        - postgresql
        - php

    - name: Crea un usuario para el código de mi aplicación
      user: name=aplicacion comment="Cuenta de la aplicacion" create_home=yes
